title: Express 57
email: jarg1985@gmail.com
description: Un libro de cuentos open source
twitter_username: jarxg
github_username:  jarxg

baseurl: "e57"
url: "https://jarxg.github.io"

markdown: kramdown

plugins:
- jekyll-mentions

jekyll-mentions: https://twitter.com

collections:
  cuentos:
    output: true
  materiales:
    output: true