title: Express 57
description: Un libro de cuentos open source

url: https://jarxg.github.io/ 
baseurl: /e57

collections:
  cuentos:
    output: true
  discografia:
    output: true
  extras:
    output: true